# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
strategy:
  matrix:
    linux_py36:
      imageName: 'ubuntu-latest'
      pythonVersion: '3.6'      
    windows_py36:
      imageName: 'windows-latest'
      pythonVersion: '3.6'    
    mac_py36:
      imageName: 'macOS-latest'
      pythonVersion: '3.6'    
    linux_py37:
      imageName: 'ubuntu-latest'
      pythonVersion: '3.7'      
    windows_py37:
      imageName: 'windows-latest'
      pythonVersion: '3.7'    
    mac_py37:
      imageName: 'macOS-latest'
      pythonVersion: '3.7'   
    linux_py38:
      imageName: 'ubuntu-latest'
      pythonVersion: '3.8'      
    windows_py38:
      imageName: 'windows-latest'
      pythonVersion: '3.8'    
    mac_py38:
      imageName: 'macOS-latest'
      pythonVersion: '3.8'
         
pool:
  vmImage: $(imageName)

steps:
# install tools (these will be cached)
- bash: |
    curl https://sh.rustup.rs -sSf | sh -s -- -y --no-modify-path --default-toolchain none
    which rustup && rustup -V && rustc --version
    rustup default nightly
  displayName: Ensure rustup is installed
- task: UsePythonVersion@0
  inputs:
      versionSpec: '$(pythonVersion)'
- bash: |
    pip install maturin
  displayName: Ensure maturin is installed
- bash: |
    maturin publish -u __token__ -p $(PYPI_TOKEN) -i $(which python)
  displayName: Push to PYPI


