# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
# install tools (these will be cached)
- bash: |
    curl https://sh.rustup.rs -sSf | sh -s -- -y --no-modify-path --default-toolchain none
    which rustup && rustup -V && rustc --version
    rustup default nightly
  displayName: Ensure rustup is installed
# - bash: |
#     cargo build
#   displayName: Cargo Build
- task: UsePythonVersion@0
  inputs:
      versionSpec: 3.6
- bash: |
    python --version
  displayName: Check Python Version
- bash: |
    pip install maturin
  displayName: Ensure maturin is installed
- bash: |
    maturin --version
  displayName: Check maturin version

# - bash: |
#     maturin publish -u __token__ -p $PYPI_TOKEN -i $(which python3)
#   displayName: Push to PYPI


